version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build: 
      # context: ./backend
      # dockerfile: Dockerfile
      # args:
        # - some-args: 1
    ports:
      - 80:80
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src  
      - /app/node_modules 
    stdin_open: true # That this service needs an open input connection
    tty: true # Connect input to show output more clear
    depends_on:
      - backend

volumes:
  data:
  logs:
